version: "3.7"
services:
  postgres:
    container_name: gl_postgres
    build:
      context: ./pkg/postgresql
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_EXTENSIONS=${POSTGRES_EXTENSIONS}
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '3001:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
  backend:
    container_name: gl_backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
     - .env
      
    depends_on:
      - postgres
    networks:
      - default
    ports:
    - "3000:3000"
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: gl_swagger_ui
    profiles:
      - swaggerapi
    ports:
    - "3002:8080"
    volumes:
    - ./doc:/usr/share/nginx/html/doc
    environment:
        # API_URL: doc/golephant-api.yaml
        URLS: "[{ url: \"doc/golephant-api.yaml\", name: \"🦕 Golephant\" },
              ]"

volumes:
  database_postgres:

networks:
  gl_postgres:
    driver: bridge