openapi: 3.0.0
info:
  title: 🦕 Golephant API documentation
  version: 1.0.0
servers:
  - url: http://localhost:3000/
paths:
  /helloWorld:
    $ref: './resources/hello-world.yaml#HelloWorld'
  /user/register:
    $ref: './resources/user.yaml#UserRegisterPath'
  /user/login:
    $ref: './resources/user.yaml#UserLogInPath'
  /user/{id}:
    $ref: './resources/user.yaml#UserUpdateDataPathWithID'
  /user/authMe:
    $ref: './resources/user.yaml#AuthMePath'
# 1) Cookie
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: Token