openapi: 3.0.0
info:
  title: 🦕 Golephant API documentation
  version: 1.0.0
servers:
  - url: http://localhost:3000/
paths:
  /helloWorld:
    $ref: './resources/hello-world.yaml#HelloWorld'
    # auth
  /auth/register/company:
    $ref: './resources/auth.yaml#RegisterCompanyPath'
  /auth/register/user:
    $ref: './resources/auth.yaml#RegisterUserPath'
  /auth/login/company:
    $ref: './resources/auth.yaml#LogInCompanyPath'
  /auth/login/user:
    $ref: './resources/auth.yaml#LogInUserPath'
  /auth/me:
    $ref: './resources/auth.yaml#AuthMePath'
    # user
  /users/{id}:
    $ref: './resources/user.yaml#UserUpdateDataPathWithID'
    # resume
  /resumes/users/{id}:
    $ref: './resources/resum.yaml#CreatePathWithID'
  /resumes/{userId}:
    $ref: './resources/resum.yaml#ListPathWithID'
  /resumes/{id}:
    $ref: './resources/resum.yaml#DeletePathWithID'
  /resumes/{resumeId}/users/{userId}/basicInfo:
    $ref: './resources/resum.yaml#UpdateBasicInfoPathWithID'
  /resumes/{resumeId}/users/{userId}/aboutMe:
    $ref: './resources/resum.yaml#UpdateAboutMePathWithID'
  /resumes/{resumeId}/users/{userId}/citizenship:
    $ref: './resources/resum.yaml#UpdateCitizenshipPathWithID'
  /resumes/{resumeId}/users/{userId}/desiredPosition:
    $ref: './resources/resum.yaml#UpdateDesiredPositionPathWithID'
  /resumes/{resumeId}/users/{userId}/tags:
    $ref: './resources/resum.yaml#UpdateTagsPathWithID'
    # specialization
  /specializations:
    $ref: './resources/specialization.yaml#SpecializationsPath'
    # resume status
  /resumeStatuses:
    $ref: './resources/resume_status.yaml#ResumeStatusesPath'
    # position types
  /positionTypes:
    $ref: './resources/position_type.yaml#PositionTypesPath'
    # company
  /companies/{companyId}/addressess:
    $ref: './resources/company.yaml#AddCompanyAdressPathWithID'
  /companies/{companyId}/addressess/{companyAddressId}:
    $ref: './resources/company.yaml#DeleteCompanyAdressPathWithID'
     # company position
  /companies/{companyId}/positions:
    $ref: './resources/company.yaml#AddPositionPathWithID'
  /companies/{companyId}/positions/{positionId}:
    $ref: './resources/company.yaml#DeletePositionPathWithID'
  /companies/{companyId}/positions/{positionId}/reponsobilities:
    $ref: './resources/company.yaml#UpdatePositionResponsobilitiesPathWithID'
  /companies/{companyId}/positions/{positionId}/requirements:
    $ref: './resources/company.yaml#UpdatePositionRequirementsPathWithID'
# 1) Cookie
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: Token